### ISSUE TITLE
Discrepancy between the pooled clustering and SCAFFOLD analysis

### ISSUE THREAD

**Issue by chiararancan** [ParkerICI/scfeatures#3]
Hi Federico,
I have been running a pooled clustering analysis using grappolo::cluster_fcs_files_groups, but then I can't use those data for the Scaffold analysis. 
It seems the problem is that grappolo produce one .txt file (all.samples.clustered.txt) with all the data, while the current Scaffold (run_scaffold_analysis) code expect to have .txt for each .fcs files.
Thank you!

Chiara

**Comment by pfgherardini** [comment]
These are two different things, and it's entirely possible to do both

If you pooled all the data together you will only have one .txt file and that will result in a single scaffold map. Using panorama you will then be able to visualize statistics for the individual samples.

If you clustered all the data independently, then you would have as many .txt files as you had fcs files, and each one of them will result in a different scaffold map.

There is always a 1:1 relationship between the .txt files and the .graphml files (i.e. the scaffold maps)

**Comment by chiararancan** [comment]
Well, neither of the two methods work at the moment.
That discrepancy was just an hypothesis we had.
The following is the error I receive when I make a pooled analysis:
<img width="1178" alt="screen shot 2018-08-23 at 6 13 30 pm" src="https://user-images.githubusercontent.com/24398856/44559756-db8ba200-a700-11e8-8ece-684ab6910197.png">

This is the error I receive when running the unpooled analysis in vite:

<img width="1174" alt="screen shot 2018-08-23 at 6 16 25 pm" src="https://user-images.githubusercontent.com/24398856/44559769-f1996280-a700-11e8-88a3-69684cadcd7f.png">

**Comment by chiararancan** [comment]
The landmark nodes are in a folder named gated and they are .fcs files.
Is the problem the fact that the system is looking for .rds files?

**Comment by pfgherardini** [comment]
The path where it is trying to write those files is very weird (way too long). What are you doing exactly? How are you launching the analysis? I need a complete description of what you are doing and data to reproduce the problem. My guess is that there is some mistake in the way you are launching the analysis

**Comment by chiararancan** [comment]
Hi Federico,

Here a detailed step by step description.

1- I perform pool clustering with grappolo with the following code:
files.groups <- list(all.samples = list.files(pattern = "*.fcs$"))
col.names <- c("CD8", "CD294", "CD160", "NKp30", "NKG2C", "CD57",
               "CD56", "CD27", "KIRs", "NKp46", "4-1BB", "CD85j", "CD28", "NKG2D", 
               "PD-1", "CD127", "CD161", "NKG2A", "NKp44", "CD16")
cluster_fcs_files_groups(files.groups, num.cores = 3, col.names = col.names, num.clusters = 200,
                         asinh.cofactor = 150, downsample.to = 10000)

As output I receive a single .rds file and a single .txt file.

2- I then run vite from the GUI:
<img width="954" alt="screen shot 2018-08-29 at 9 57 41 am" src="https://user-images.githubusercontent.com/24398856/44803031-19118480-ab72-11e8-90bb-97d7e0b83c46.png">

And this is the set up of my directory:
<img width="505" alt="screen shot 2018-08-29 at 9 57 50 am" src="https://user-images.githubusercontent.com/24398856/44803058-29296400-ab72-11e8-8074-de1768f3985b.png">

And then I get the error:
<img width="1161" alt="screen shot 2018-08-29 at 10 01 30 am" src="https://user-images.githubusercontent.com/24398856/44803185-9210dc00-ab72-11e8-816f-3f48544cd2dd.png">

Since it seems to be a problem with the landmark nodes, I tried to make the nodes in different ways but I receive always the same error. 
I hope it helps.

**Comment by chiararancan** [comment]
It's just weird because in the error it talk of a .rds file which obviously I don't have, because the landmark nodes are .fcs files.

**Comment by chiararancan** [comment]
I will send you the data I am using via box

**Comment by pfgherardini** [comment]
This was a problem in `vite` and was solved by https://github.com/ParkerICI/vite/commit/6d9ca47784d9a3709074d3f3e6edc998525d38a2
