### ISSUE TITLE
no RData or txt files created after pooled clustering in grappolo

### ISSUE THREAD

**Issue by CNicholasMDA** [ParkerICI/scfeatures#4]
Hi,
I'm having similar issues with grappolo as in the past, except now I am attempting to generate pooled clusters using the clustering_GUI().  Is it reasonable to suspect the same cause as before? 
("The problem is due to the use of parallel::mclapply when called from a shiny app. I have opened an issue on the shiny github and will keep you posted rstudio/shiny#2163...")
I do not get an error message in R Studio, but the same symptoms persist: successful clustering message window pops up instantaneously, while no RData or .txt files are generated. Again, in MacOS.

**Comment by pfgherardini** [comment]
This turned out not to be a bug. I need to add an error message when in pooled clustering mode no clustering group is created in the GUI

**Comment by CNicholasMDA** [comment]
Thanks Federico! Problem solved.
