### ISSUE TITLE
question about output files from grappolo

### ISSUE THREAD

**Issue by CNicholasMDA** [ParkerICI/scfeatures#5]
Hi Federico - is there a way to generate .fcs files after clustering in grappolo?  Or rather, is there a script that can convert .RData files from grappolo to .fcs?

Asking for my team, as they had previously analyzed data in SCAFFoLD, used a script to create .fcs files, then opened the resulting .fcs file in a different program such as cyt3, etc.

Please let me know if my question is unclear.

**Comment by pfgherardini** [comment]
You can do it this way

```R
library(premessa) #Need to use some functions that are in the premessa pacakge
tab <- readRDS("your_file.rds")
flow.frame <- as_flowFrame(as.matrix(tab))
write_flowFrame(flow.frame, "you_file.fcs")
```

Note that the values in the RDS file are already asinh transformed, so they should be visualized on a linear scale (for instance in flowJo)
